version: '3.1'

services:
  db:
    restart: always
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root