server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  output:
    ansi:
      enabled: always
  redis:
    port: 6379
    host: redis
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql : true

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

spring-doc:
  swagger-ui:
    tags-sorter: alpha